VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Cls4_Log"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Public runDateTime As String
Public userName As String
Public folderPath As String
Public fileName As String
Public errorCord As String
Public totalRecord As Long
Public readRecord As Long
Public errorRecord As Long
Public processStatus As String
Public timeSpent As Double
Public errorRow As Long
Public errorReason As String
Public relevantData As String
